apiVersion: v1
kind: Pod
metadata:
   name: my-ip-app
spec:
    containers:
     - name: ip-app
       image: shankaru/new_repo:v1
       ports:
         - containerPort: 80 
       env: 
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
               name: my-configmap
               key: env
        - name: APP
          valueFrom:
            configMapKeyRef:
               name: my-configmap
               key: app