apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-sa-cluster-role
rules:
  - apiGroups: [""]
    resources: ["depolyments"]
    verbs: ["get", "list", "update", "create", "delete"]
    