apiVersion: apps/v1
kind: DaemonSet
metadata:
   name: nginx-daemonset
spec:
    template:
        metadata:
            labels:
              app: my-nginx-daemonset
        spec:
           containers:
              - name: nginx-daemonset
                image: nginx:1.22.1
                ports:
                 - containerPort: 80 
    selector:
        matchLabels:
           app: my-nginx-daemonset           