apiVersion: apps/v1
kind: Deployment
metadata:
   name: ip-app-deployment
spec:
    replicas: 4
    template:
        metadata:
            labels:
              app: ip-app
        spec:
           containers:
              - name: ip-app
                image: shankaru/new_repo:v1
                ports:
                 - containerPort: 80 
    selector:
        matchLabels:
           app: ip-app           