apiVersion: apps/v1
kind: Pod
metadata:
   name: nginx-depolyment
spec:
    replicas: 4
    template:
        metadata:
           label:
              app: my-nginx
        spec:
           containers:
              - name: nginx
                image: nginx
                ports:
                 - containerPort: 80 
    selector:
        matchLabels:
           app: my-nginx           