apiVersion: apps/v1
kind: StatefulSet
metadata:
   name: ip-app-statefulset
spec:
    replicas: 4
    template:
        metadata:
            labels:
              app: ip-app-sfs
        spec:
           containers:
              - name: ipapp
                image: shankaru/new_repo:v1
                ports:
                 - containerPort: 8080
    selector:
        matchLabels:
           app: ip-app-sfs  

---
apiVersion: v1
kind: Service
metadata:
   name: ip-app-headless-svc
spec:
   clusterIP: None
   selector: 
       app: ip-app-sfs
   ports: 
     - name: http
       port: 30006
       targetPort: 8080