apiVersion: v1
kind: Pod
metadata:
   name: my-ip-app-init-container
spec:
    initContainers:
     - name: busybox
       image: busybox
       command: ["/bin/bash"]
       args: ["-c","echo '<html><h1>Init container</h1></html>'>> /shareDir/index.html"]
       volumeMounts:
        - name: shareDirectory
          mountPath: "/shareDir"

    containers:
     - name: nginx
       image: nginx
       ports:
         - containerPort: 80 
       volumeMounts:
        - name: shareDirectory
          mountPath: "/usr/share/nginx/html"

    volumes:
     - name: shareDirectory
       emptyDir: 