apiVersion: v1
kind: Pod
metadata:
   name: my-ip-app-sidecar-container
spec:
    containers:
     - name: nginx
       image: nginx
       ports:
         - containerPort: 80 
       volumeMounts:
        - name: sharelogs
          mountPath: "/var/log/nginx"
          
     - name: busybox-sharelogs
       image: busybox
       command: ["/bin/sh"]
       args: ["-c","count=0; while true; do count=$((count++)); echo -----------$count -------------; cat /var/log/nginx/access.log; /var/log/nginx/error.log; sleep 5; done"]
       volumeMounts:
        - name: sharelogs
          mountPath: "/var/log/nginx"

    volumes:
     - name: sharelogs
       emptyDir: 