apiVersion: v1
kind: PersistentVolume
metadata:
  name: aws-ebs-pv
spec:
    awsElasticBlockStore:
      volumeID: vol-0da0d35a549d93cbf
      fsType: xfs
    accessModes:
      - ReadWriteMany
    capacity:
       storage: 4Gi