apiVersion: v1
kind: PersistentVolume
metadata:
  name: aws-pv
spec:
    awsElasticBlockStore:
      volumeID: 
      fsType: xfs
    accessModes:
      - ReadWriteMany
    capacity:
       storage: 4Gi
    hostPath: 
       path: 'home/ubuntu/'  
